#!/bin/bash
echo "CPU型号:    "

sysctl -n machdep.cpu.brand_string

echo "CPU核心数:  "

sysctl -n machdep.cpu.core_count

echo "CPU线程数:  "

sysctl -n machdep.cpu.thread_count

echo "其它信息："

system_profiler SPDisplaysDataType SPMemoryDataType SPStorageDataType | grep 'Graphics/Displays:\|Chipset Model:\|VRAM (Total):\|Resolution:\|Memory Slots:\|Size:\|Speed:\|Storage:\|Media Name:\|Medium Type:'
