#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	    CREATE USER $PGUSER SUPERUSER ENCRYPTED PASSWORD '$PGPASSWORD';
	    CREATE DATABASE $PGDATABASE;
	    GRANT ALL PRIVILEGES ON DATABASE $PGDATABASE TO $PGUSER;
	    CREATE USER $PG_REPLICATION_USER REPLICATION LOGIN ENCRYPTED PASSWORD '$PG_REPLICATION_PASSWD';
EOSQL
