- name: run apt update
  apt:
    update_cache: yes

- name: Install Python pip
  apt: name={{ item }} update_cache=true state=present force_apt_get=yes
  with_items:
  - python-pip
  - python3-pip
  become: true

- name: install packages
  apt:
    name: "{{ common_packages + ubuntu_packages}}"
    state: present