- set_fact:
    deploy_dir: "/home/{{ user }}/prometheus/"

- name: copy etc folder
  synchronize:
    src: "etc"
    dest: "{{ deploy_dir }}"
    delete: yes
    recursive: yes
    archive: no
  become: yes

- name: generate configs
  template:
    src: "{{ item }}"
    dest: "{{ deploy_dir}}/{{ item | replace('.j2', '') | replace(role_path + '/templates/', '') }}"
  with_lines:
    - "find {{ role_path }}/templates -type f -name '*.j2'"
  become: yes

- name: validate yaml files
  shell: "docker run --rm -v {{ deploy_dir }}:/yaml  sdesbure/yamllint yamllint -d '{extends: relaxed, rules: {line-length: disable}}' ."

- name: run prometheus
  shell: docker-compose up -d
  args:
    chdir: "{{ deploy_dir }}"

- name: ensure(wait for) prometheus starts
  wait_for:
    port: 9090
    timeout: 100

- name: reload prometheus
  shell: curl --silent -XPOST localhost:9090/-/reload
  args:
    warn: False
